(load "primitive.scm")
(load "env.scm")
(load "read-expr.scm")
(load "eval-expr.scm")
(load "special-forms.scm")
(load "built-in.scm")
(load "built-in-arithmetic.scm")
(load "built-in-pred.scm")
(load "built-in-string.scm")
(load "built-in-io.scm")
(load "repl.scm")

(repl)
